Admin/Controllers/FacultyController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Admin.Models;
namespace Admin.Controllers
{
    public class FacultyController : Controller
    {
        private readonly FacultyRepo _context;

        public FacultyController(FacultyRepo context)
        {
            _context = context;
        }


        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Login(Login model)
        {
            bool isValid = _context.Login.Any(x => x.UserName == model.UserName && x.Password == model.Password);
            if (isValid)
            {
                return RedirectToAction(nameof(Admin));
            }
            else
            {
                ModelState.AddModelError("", "Invalid UserName and Password");
            }
            return View();
        }

        public IActionResult AcademyPortal()
        {
            return View();
        }
        public IActionResult FacultyRegistration()
        {
            return View();
        }
        public IActionResult BatchAllocations()
        {
            return View();
        }
        public IActionResult AwardandCreditpoint()
        {
            return View();
        }

        public IActionResult Admin()
        {
            
            return View();
        }
        public async Task<IActionResult> Index3()
        {
            return View(await _context.Faculty.ToListAsync());

        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Faculty sales)
        {
            if (ModelState.IsValid)
            {
                _context.Add(sales);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index3));
            }
            return View(sales);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index3");
            }
            var mod = await _context.Faculty.FindAsync(id);
            return View(mod);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Faculty sales)
        {
            if (ModelState.IsValid)
            {
                _context.Update(sales);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index3");
            }
            return View(sales);
        }

        [HttpGet]
        public async Task<IActionResult> FactEdit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index3");
            }
            var mod = await _context.Faculty.FindAsync(id);
            return View(mod);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> FactEdit(Faculty sales)
        {
            if (ModelState.IsValid)
            {
                _context.Update(sales);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index3");
            }
            return View(sales);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var sales = await _context.Faculty.FirstAsync(m => m.Faculty_Id == id);
            if (sales == null)
            {
                return NotFound();
            }
            return View(sales);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirm(int id)
        {
            var sales = await _context.Faculty.FindAsync(id);
            _context.Faculty.Remove(sales);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index3));
        }
        [HttpGet]
        public async Task<IActionResult> FactDelete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var sales = await _context.Faculty.FirstAsync(m => m.Faculty_Id == id);
            if (sales == null)
            {
                return NotFound();
            }
            return View(sales);
        }
        [HttpPost, ActionName("FactDelete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> FactDeleteConfirm(int id)
        {
            var sales = await _context.Faculty.FindAsync(id);
            _context.Faculty.Remove(sales);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index3));
        }

    

public async Task<IActionResult> Index4()
        {
            return View(await _context.FacultySkill.ToListAsync());

        }

        public IActionResult Create1()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create1(FacultySkill sales)
        {
            if (ModelState.IsValid)
            {
                _context.Add(sales);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index4));
            }
            return View(sales);
        }
        [HttpGet]
        public async Task<IActionResult> Edit1(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index4");
            }
            var mod = await _context.FacultySkill.FindAsync(id);
            return View(mod);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit1(FacultySkill sales)
        {
            if (ModelState.IsValid)
            {
                _context.Update(sales);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index4");
            }
            return View(sales);
        }

        [HttpGet]
        public async Task<IActionResult> FactEdit1(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index4");
            }
            var mod = await _context.FacultySkill.FindAsync(id);
            return View(mod);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> FactEdit1(FacultySkill sales)
        {
            if (ModelState.IsValid)
            {
                _context.Update(sales);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index4");
            }
            return View(sales);
        }
        [HttpGet]
        public async Task<IActionResult> Delete1(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var sales = await _context.FacultySkill.FirstAsync(m => m.Faculty_Id == id);
            if (sales == null)
            {
                return NotFound();
            }
            return View(sales);
        }
        [HttpPost, ActionName("Delete1")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirm1(int id)
        {
            var sales = await _context.FacultySkill.FindAsync(id);
            _context.FacultySkill.Remove(sales);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index4));
        }
        [HttpGet]
        public async Task<IActionResult> FactDelete1(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var sales = await _context.FacultySkill.FirstAsync(m => m.Faculty_Id == id);
            if (sales == null)
            {
                return NotFound();
            }
            return View(sales);
        }
        [HttpPost, ActionName("FactDelete1")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> FactDeleteConfirm1(int id)
        {
            var sales = await _context.Faculty.FindAsync(id);
            _context.Faculty.Remove(sales);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index4));
        }

        public async Task<IActionResult> Module()
        {
            return View(await _context.Module.ToListAsync());

        }
        public IActionResult Create2()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create2(Module sales)
        {
            if (ModelState.IsValid)
            {
                _context.Add(sales);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Module));
            }
            return View(sales);
        }
        [HttpGet]
        public async Task<IActionResult> Edit2(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Module");
            }
            var mod = await _context.Module.FindAsync(id);
            return View(mod);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit2(Module sales)
        {
            if (ModelState.IsValid)
            {
                _context.Update(sales);
                await _context.SaveChangesAsync();
                return RedirectToAction("Module");
            }
            return View(sales);
        }

        [HttpGet]
        public async Task<IActionResult> ModEdit2(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Module");
            }
            var mod = await _context.Module.FindAsync(id);

Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Admin</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                @*<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>*@
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Faculty" asp-action="Login">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Faculty" asp-action="Admin">Adminpage</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Faculty" asp-action="AcademyPortal">AcademyPortal</a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Faculty" asp-action="Index3">Index3</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Faculty" asp-action="Index4">Index4</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Faculty" asp-action="Module">Module</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Faculty" asp-action="Batch">Batch</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Faculty" asp-action="Batchupdate">Batchupdate</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Faculty" asp-action="Report">Report</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Faculty" asp-action="Award">Award</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Faculty" asp-action="credit">credit</a>
                        </li>*@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @*<footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2021 - Login_Page - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>